// <auto-generated />
using System;
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OpenFoodUploader.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Database.Models.Additive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdditiveTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("additive_type_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Risk")
                        .HasColumnType("integer")
                        .HasColumnName("risk");

                    b.HasKey("Id");

                    b.HasIndex("AdditiveTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("additives", null, t =>
                        {
                            t.HasCheckConstraint("CK_Additives_Risk_ValidValues", "risk IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Backend.Database.Models.AdditiveHealthRisk", b =>
                {
                    b.Property<int>("AdditiveId")
                        .HasColumnType("integer")
                        .HasColumnName("additive_id");

                    b.Property<int>("HealthRiskId")
                        .HasColumnType("integer")
                        .HasColumnName("health_risk_id");

                    b.HasKey("AdditiveId", "HealthRiskId");

                    b.HasIndex("HealthRiskId")
                        .HasDatabaseName("idx_additive_health_risks_health_risk");

                    b.ToTable("additive_health_risks", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.AdditiveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("additive_types", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("allergens", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_categories_name_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.FoodGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_food_groups_name_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("food_groups", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.HealthRisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("health_risks", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.Product", b =>
                {
                    b.Property<decimal>("Code")
                        .HasColumnType("numeric")
                        .HasColumnName("code");

                    b.Property<decimal?>("AddedSugars100g")
                        .HasColumnType("numeric")
                        .HasColumnName("added-sugars_100g");

                    b.Property<decimal?>("Alcohol100g")
                        .HasColumnType("numeric")
                        .HasColumnName("alcohol_100g");

                    b.Property<decimal?>("AlphaLinolenicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("alpha_linolenic_acid_100g");

                    b.Property<decimal?>("ArachidicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("arachidic_acid_100g");

                    b.Property<decimal?>("ArachidonicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("arachidonic_acid_100g");

                    b.Property<decimal?>("BehenicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("behenic_acid_100g");

                    b.Property<decimal?>("BetaCarotene100g")
                        .HasColumnType("numeric")
                        .HasColumnName("beta_carotene_100g");

                    b.Property<decimal?>("Bicarbonate100g")
                        .HasColumnType("numeric")
                        .HasColumnName("bicarbonate_100g");

                    b.Property<decimal?>("Biotin100g")
                        .HasColumnType("numeric")
                        .HasColumnName("biotin_100g");

                    b.Property<decimal?>("ButyricAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("butyric_acid_100g");

                    b.Property<decimal?>("Caffeine100g")
                        .HasColumnType("numeric")
                        .HasColumnName("caffeine_100g");

                    b.Property<decimal?>("Calcium100g")
                        .HasColumnType("numeric")
                        .HasColumnName("calcium_100g");

                    b.Property<decimal?>("CapricAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("capric_acid_100g");

                    b.Property<decimal?>("CaproicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("caproic_acid_100g");

                    b.Property<decimal?>("CaprylicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("caprylic_acid_100g");

                    b.Property<decimal?>("Carbohydrates100g")
                        .HasColumnType("numeric")
                        .HasColumnName("carbohydrates_100g");

                    b.Property<decimal?>("Casein100g")
                        .HasColumnType("numeric")
                        .HasColumnName("casein_100g");

                    b.Property<decimal?>("CeroticAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("cerotic_acid_100g");

                    b.Property<decimal?>("Chloride100g")
                        .HasColumnType("numeric")
                        .HasColumnName("chloride_100g");

                    b.Property<decimal?>("Cholesterol100g")
                        .HasColumnType("numeric")
                        .HasColumnName("cholesterol_100g");

                    b.Property<decimal?>("Chromium100g")
                        .HasColumnType("numeric")
                        .HasColumnName("chromium_100g");

                    b.Property<decimal?>("Completeness")
                        .HasColumnType("numeric")
                        .HasColumnName("completeness");

                    b.Property<decimal?>("Copper100g")
                        .HasColumnType("numeric")
                        .HasColumnName("copper_100g");

                    b.Property<decimal?>("DihomoGammaLinolenicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("dihomo_gamma_linolenic_acid_100g");

                    b.Property<decimal?>("DocosahexaenoicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("docosahexaenoic_acid_100g");

                    b.Property<decimal?>("EicosapentaenoicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("eicosapentaenoic_acid_100g");

                    b.Property<decimal?>("ElaidicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("elaidic_acid_100g");

                    b.Property<decimal?>("EnergyFromFat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("energy-from-fat_100g");

                    b.Property<decimal?>("EnergyKcal100g")
                        .HasColumnType("numeric")
                        .HasColumnName("energy-kcal_100g");

                    b.Property<decimal?>("EnvironmentalScore")
                        .HasColumnType("numeric")
                        .HasColumnName("environmental_score_score");

                    b.Property<decimal?>("ErucicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("erucic_acid_100g");

                    b.Property<decimal?>("Erythritol100g")
                        .HasColumnType("numeric")
                        .HasColumnName("erythritol_100g");

                    b.Property<decimal?>("Fat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fat_100g");

                    b.Property<decimal?>("Fiber100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fiber_100g");

                    b.Property<decimal?>("Fluoride100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fluoride_100g");

                    b.Property<decimal?>("Folates100g")
                        .HasColumnType("numeric")
                        .HasColumnName("folates_100g");

                    b.Property<decimal?>("Fructose100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fructose_100g");

                    b.Property<decimal?>("FruitsVegetablesNutsEstimateFromIngredients100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fruits_vegetables_nuts_estimate_from_ingredients_100g");

                    b.Property<decimal?>("Galactose100g")
                        .HasColumnType("numeric")
                        .HasColumnName("galactose_100g");

                    b.Property<decimal?>("GammaLinolenicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("gamma_linolenic_acid_100g");

                    b.Property<decimal?>("Glucose100g")
                        .HasColumnType("numeric")
                        .HasColumnName("glucose_100g");

                    b.Property<decimal?>("GondoicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("gondoic_acid_100g");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<decimal?>("InsolubleFiber100g")
                        .HasColumnType("numeric")
                        .HasColumnName("insoluble_fiber_100g");

                    b.Property<decimal?>("Iodine100g")
                        .HasColumnType("numeric")
                        .HasColumnName("iodine_100g");

                    b.Property<decimal?>("Iron100g")
                        .HasColumnType("numeric")
                        .HasColumnName("iron_100g");

                    b.Property<decimal?>("Isomalt100g")
                        .HasColumnType("numeric")
                        .HasColumnName("isomalt_100g");

                    b.Property<decimal?>("Lactose100g")
                        .HasColumnType("numeric")
                        .HasColumnName("lactose_100g");

                    b.Property<string>("LastImageDatetime")
                        .HasColumnType("text")
                        .HasColumnName("last_image_datetime");

                    b.Property<string>("LastModifiedDatetime")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_datetime");

                    b.Property<decimal?>("LauricAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("lauric_acid_100g");

                    b.Property<decimal?>("LignocericAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("lignoceric_acid_100g");

                    b.Property<decimal?>("LinoleicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("linoleic_acid_100g");

                    b.Property<decimal?>("Magnesium100g")
                        .HasColumnType("numeric")
                        .HasColumnName("magnesium_100g");

                    b.Property<decimal?>("Maltitol100g")
                        .HasColumnType("numeric")
                        .HasColumnName("maltitol_100g");

                    b.Property<decimal?>("Maltodextrins100g")
                        .HasColumnType("numeric")
                        .HasColumnName("maltodextrins_100g");

                    b.Property<decimal?>("Maltose100g")
                        .HasColumnType("numeric")
                        .HasColumnName("maltose_100g");

                    b.Property<decimal?>("Manganese100g")
                        .HasColumnType("numeric")
                        .HasColumnName("manganese_100g");

                    b.Property<decimal?>("MeadAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("mead_acid_100g");

                    b.Property<decimal?>("MelissicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("melissic_acid_100g");

                    b.Property<decimal?>("Methylsulfonylmethane100g")
                        .HasColumnType("numeric")
                        .HasColumnName("methylsulfonylmethane_100g");

                    b.Property<decimal?>("Molybdenum100g")
                        .HasColumnType("numeric")
                        .HasColumnName("molybdenum_100g");

                    b.Property<decimal?>("MonounsaturatedFat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("monounsaturated_fat_100g");

                    b.Property<decimal?>("MontanicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("montanic_acid_100g");

                    b.Property<decimal?>("MyristicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("myristic_acid_100g");

                    b.Property<decimal?>("NervonicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("nervonic_acid_100g");

                    b.Property<int?>("NovaGroup")
                        .HasColumnType("integer")
                        .HasColumnName("nova_group");

                    b.Property<decimal?>("Nucleotides100g")
                        .HasColumnType("numeric")
                        .HasColumnName("nucleotides_100g");

                    b.Property<decimal?>("OleicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("oleic_acid_100g");

                    b.Property<decimal?>("Omega3Fat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("omega_3_fat_100g");

                    b.Property<decimal?>("Omega6Fat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("omega_6_fat_100g");

                    b.Property<decimal?>("Omega9Fat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("omega_9_fat_100g");

                    b.Property<decimal?>("PalmiticAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("palmitic_acid_100g");

                    b.Property<decimal?>("PantothenicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("pantothenic_acid_100g");

                    b.Property<decimal?>("Ph100g")
                        .HasColumnType("numeric")
                        .HasColumnName("ph_100g");

                    b.Property<decimal?>("Phosphorus100g")
                        .HasColumnType("numeric")
                        .HasColumnName("phosphorus_100g");

                    b.Property<decimal?>("Polyols100g")
                        .HasColumnType("numeric")
                        .HasColumnName("polyols_100g");

                    b.Property<decimal?>("PolyunsaturatedFat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("polyunsaturated_fat_100g");

                    b.Property<decimal?>("Potassium100g")
                        .HasColumnType("numeric")
                        .HasColumnName("potassium_100g");

                    b.Property<string>("ProductBrand")
                        .HasColumnType("text")
                        .HasColumnName("brands");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<decimal?>("Proteins100g")
                        .HasColumnType("numeric")
                        .HasColumnName("proteins_100g");

                    b.Property<decimal?>("Psicose100g")
                        .HasColumnType("numeric")
                        .HasColumnName("psicose_100g");

                    b.Property<decimal?>("Salt100g")
                        .HasColumnType("numeric")
                        .HasColumnName("salt_100g");

                    b.Property<decimal?>("SaturatedFat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("saturated-fat_100g");

                    b.Property<decimal?>("Selenium100g")
                        .HasColumnType("numeric")
                        .HasColumnName("selenium_100g");

                    b.Property<decimal?>("SerumProteins100g")
                        .HasColumnType("numeric")
                        .HasColumnName("serum_proteins_100g");

                    b.Property<decimal?>("Silica100g")
                        .HasColumnType("numeric")
                        .HasColumnName("silica_100g");

                    b.Property<decimal?>("Sodium100g")
                        .HasColumnType("numeric")
                        .HasColumnName("sodium_100g");

                    b.Property<decimal?>("SolubleFiber100g")
                        .HasColumnType("numeric")
                        .HasColumnName("soluble_fiber_100g");

                    b.Property<decimal?>("Sorbitol100g")
                        .HasColumnType("numeric")
                        .HasColumnName("sorbitol_100g");

                    b.Property<decimal?>("Starch100g")
                        .HasColumnType("numeric")
                        .HasColumnName("starch_100g");

                    b.Property<decimal?>("StearicAcid100g")
                        .HasColumnType("numeric")
                        .HasColumnName("stearic_acid_100g");

                    b.Property<decimal?>("Sucrose100g")
                        .HasColumnType("numeric")
                        .HasColumnName("sucrose_100g");

                    b.Property<decimal?>("Sugars100g")
                        .HasColumnType("numeric")
                        .HasColumnName("sugars_100g");

                    b.Property<decimal?>("Taurine100g")
                        .HasColumnType("numeric")
                        .HasColumnName("taurine_100g");

                    b.Property<decimal?>("TransFat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("trans-fat_100g");

                    b.Property<decimal?>("UnsaturatedFat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("unsaturated_fat_100g");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<decimal?>("VitaminA100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin-a_100g");

                    b.Property<decimal?>("VitaminB12_100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin_b12_100g");

                    b.Property<decimal?>("VitaminB1_100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin_b1_100g");

                    b.Property<decimal?>("VitaminB2_100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin_b2_100g");

                    b.Property<decimal?>("VitaminB6_100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin_b6_100g");

                    b.Property<decimal?>("VitaminB9_100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin_b9_100g");

                    b.Property<decimal?>("VitaminC100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin-c_100g");

                    b.Property<decimal?>("VitaminD100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin_d_100g");

                    b.Property<decimal?>("VitaminE100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin_e_100g");

                    b.Property<decimal?>("VitaminK100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin_k_100g");

                    b.Property<decimal?>("VitaminPp100g")
                        .HasColumnType("numeric")
                        .HasColumnName("vitamin_pp_100g");

                    b.Property<decimal?>("Zinc100g")
                        .HasColumnType("numeric")
                        .HasColumnName("zinc_100g");

                    b.Property<int?>("nutriScore")
                        .HasColumnType("integer")
                        .HasColumnName("nutriscore_score");

                    b.HasKey("Code");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("idx_products_product_name_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ProductName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ProductName"), new[] { "gin_trgm_ops" });

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.ProductAdditive", b =>
                {
                    b.Property<decimal>("ProductCode")
                        .HasColumnType("numeric")
                        .HasColumnName("product_code");

                    b.Property<int>("AdditiveId")
                        .HasColumnType("integer")
                        .HasColumnName("additive_id");

                    b.HasKey("ProductCode", "AdditiveId");

                    b.HasIndex("AdditiveId")
                        .HasDatabaseName("idx_product_additives_additive");

                    b.ToTable("product_additives", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.ProductAllergen", b =>
                {
                    b.Property<decimal>("ProductCode")
                        .HasColumnType("numeric")
                        .HasColumnName("product_code");

                    b.Property<int>("AllergenId")
                        .HasColumnType("integer")
                        .HasColumnName("allergen_id");

                    b.HasKey("ProductCode", "AllergenId");

                    b.HasIndex("AllergenId")
                        .HasDatabaseName("idx_product_allergens_allergen");

                    b.ToTable("product_allergens", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.ProductCategory", b =>
                {
                    b.Property<decimal>("ProductCode")
                        .HasColumnType("numeric")
                        .HasColumnName("product_code");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("ProductCode", "CategoryId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_product_categories_category");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.ProductCountry", b =>
                {
                    b.Property<decimal>("ProductCode")
                        .HasColumnType("numeric")
                        .HasColumnName("product_code");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.HasKey("ProductCode", "CountryId");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("idx_product_countries_country");

                    b.ToTable("product_countries", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.ProductFoodGroup", b =>
                {
                    b.Property<decimal>("ProductCode")
                        .HasColumnType("numeric")
                        .HasColumnName("product_code");

                    b.Property<int>("FoodGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("food_group_id");

                    b.HasKey("ProductCode", "FoodGroupId");

                    b.HasIndex("FoodGroupId")
                        .HasDatabaseName("idx_product_food_groups_food_group");

                    b.ToTable("product_food_groups", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.ProductHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ProductCode")
                        .HasColumnType("numeric")
                        .HasColumnName("product_code");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.HasIndex("ScannedAt");

                    b.HasIndex("UserId");

                    b.ToTable("product_history", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.ProductIngredient", b =>
                {
                    b.Property<decimal>("ProductCode")
                        .HasColumnType("numeric")
                        .HasColumnName("product_code");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.HasKey("ProductCode", "IngredientId");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("idx_product_ingredients_ingredient");

                    b.ToTable("product_ingredients", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.ProductLabel", b =>
                {
                    b.Property<decimal>("ProductCode")
                        .HasColumnType("numeric")
                        .HasColumnName("product_code");

                    b.Property<int>("LabelId")
                        .HasColumnType("integer")
                        .HasColumnName("label_id");

                    b.HasKey("ProductCode", "LabelId");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("idx_product_labels_label");

                    b.ToTable("product_labels", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppleId")
                        .HasColumnType("text")
                        .HasColumnName("apple_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_premium");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastRevenuecatEvent")
                        .HasColumnType("text")
                        .HasColumnName("last_revenuecat_event");

                    b.Property<DateTime?>("PremiumExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("premium_expiration");

                    b.Property<string>("RevenuecatId")
                        .HasColumnType("text")
                        .HasColumnName("revenuecat_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.UserFavoriteProduct", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal>("ProductCode")
                        .HasColumnType("numeric")
                        .HasColumnName("product_code");

                    b.Property<DateTime>("FavoritedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("favorited_at");

                    b.HasKey("UserId", "ProductCode");

                    b.HasIndex("FavoritedAt");

                    b.HasIndex("ProductCode");

                    b.ToTable("user_favorite_products", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Models.Additive", b =>
                {
                    b.HasOne("Backend.Database.Models.AdditiveType", "AdditiveType")
                        .WithMany("Additives")
                        .HasForeignKey("AdditiveTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdditiveType");
                });

            modelBuilder.Entity("Backend.Database.Models.AdditiveHealthRisk", b =>
                {
                    b.HasOne("Backend.Database.Models.Additive", "Additive")
                        .WithMany("AdditiveHealthRisks")
                        .HasForeignKey("AdditiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.HealthRisk", "HealthRisk")
                        .WithMany("AdditiveHealthRisks")
                        .HasForeignKey("HealthRiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Additive");

                    b.Navigation("HealthRisk");
                });

            modelBuilder.Entity("Backend.Database.Models.ProductAdditive", b =>
                {
                    b.HasOne("Backend.Database.Models.Additive", "Additive")
                        .WithMany()
                        .HasForeignKey("AdditiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.Product", "Product")
                        .WithMany("ProductAdditives")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Additive");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Database.Models.ProductAllergen", b =>
                {
                    b.HasOne("Backend.Database.Models.Allergen", "Allergen")
                        .WithMany("ProductAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.Product", "Product")
                        .WithMany("ProductAllergens")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Database.Models.ProductCategory", b =>
                {
                    b.HasOne("Backend.Database.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Database.Models.ProductCountry", b =>
                {
                    b.HasOne("Backend.Database.Models.Country", "Country")
                        .WithMany("ProductCountries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.Product", "Product")
                        .WithMany("ProductCountries")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Database.Models.ProductFoodGroup", b =>
                {
                    b.HasOne("Backend.Database.Models.FoodGroup", "FoodGroup")
                        .WithMany("ProductFoodGroups")
                        .HasForeignKey("FoodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.Product", "Product")
                        .WithMany("ProductFoodGroups")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodGroup");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Database.Models.ProductHistory", b =>
                {
                    b.HasOne("Backend.Database.Models.Product", "Product")
                        .WithMany("ProductHistories")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.User", "User")
                        .WithMany("ProductHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Models.ProductIngredient", b =>
                {
                    b.HasOne("Backend.Database.Models.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.Product", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Database.Models.ProductLabel", b =>
                {
                    b.HasOne("Backend.Database.Models.Label", "Label")
                        .WithMany("ProductLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.Product", "Product")
                        .WithMany("ProductLabels")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Database.Models.RefreshToken", b =>
                {
                    b.HasOne("Backend.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Models.UserFavoriteProduct", b =>
                {
                    b.HasOne("Backend.Database.Models.Product", "Product")
                        .WithMany("UserFavorites")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.User", "User")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Models.Additive", b =>
                {
                    b.Navigation("AdditiveHealthRisks");
                });

            modelBuilder.Entity("Backend.Database.Models.AdditiveType", b =>
                {
                    b.Navigation("Additives");
                });

            modelBuilder.Entity("Backend.Database.Models.Allergen", b =>
                {
                    b.Navigation("ProductAllergens");
                });

            modelBuilder.Entity("Backend.Database.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Backend.Database.Models.Country", b =>
                {
                    b.Navigation("ProductCountries");
                });

            modelBuilder.Entity("Backend.Database.Models.FoodGroup", b =>
                {
                    b.Navigation("ProductFoodGroups");
                });

            modelBuilder.Entity("Backend.Database.Models.HealthRisk", b =>
                {
                    b.Navigation("AdditiveHealthRisks");
                });

            modelBuilder.Entity("Backend.Database.Models.Ingredient", b =>
                {
                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("Backend.Database.Models.Label", b =>
                {
                    b.Navigation("ProductLabels");
                });

            modelBuilder.Entity("Backend.Database.Models.Product", b =>
                {
                    b.Navigation("ProductAdditives");

                    b.Navigation("ProductAllergens");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductCountries");

                    b.Navigation("ProductFoodGroups");

                    b.Navigation("ProductHistories");

                    b.Navigation("ProductIngredients");

                    b.Navigation("ProductLabels");

                    b.Navigation("UserFavorites");
                });

            modelBuilder.Entity("Backend.Database.Models.User", b =>
                {
                    b.Navigation("FavoriteProducts");

                    b.Navigation("ProductHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
